name: Cargo Build & Test
# from the cargo Book      - name: Cache
on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --release

